import DogBreed from "./DogBreed";

const DOG_BREEDS = [
  { id: DogBreed.Unselected, label: "Please select a dog breed..." },
  { id: DogBreed.Affenpinscher, label: "Affenpinscher" },
  { id: DogBreed.African, label: "African" },
  { id: DogBreed.Airedale, label: "Airedale" },
  { id: DogBreed.Akita, label: "Akita" },
  { id: DogBreed.Appenzeller, label: "Appenzeller" },
  { id: DogBreed.AustralianShepherd, label: "Shepherd Australian" },
  { id: DogBreed.Basenji, label: "Basenji" },
  { id: DogBreed.Beagle, label: "Beagle" },
  { id: DogBreed.Bluetick, label: "Bluetick" },
  { id: DogBreed.Borzoi, label: "Borzoi" },
  { id: DogBreed.Bouvier, label: "Bouvier" },
  { id: DogBreed.Boxer, label: "Boxer" },
  { id: DogBreed.Brabancon, label: "Brabancon" },
  { id: DogBreed.Briard, label: "Briard" },
  { id: DogBreed.BuhundNorwegian, label: "Norwegian Buhund" },
  { id: DogBreed.BulldogBoston, label: "Boston Bulldog" },
  { id: DogBreed.BulldogEnglish, label: "English Bulldog" },
  { id: DogBreed.BulldogFrench, label: "French Bulldog" },
  { id: DogBreed.BullterrierStaffordshire, label: "Staffordshire Bullterrier" },
  { id: DogBreed.CattledogAustralian, label: "Australian Cattledog" },
  { id: DogBreed.Chihuahua, label: "Chihuahua" },
  { id: DogBreed.Chow, label: "Chow" },
  { id: DogBreed.Clumber, label: "Clumber" },
  { id: DogBreed.Cockapoo, label: "Cockapoo" },
  { id: DogBreed.CollieBorder, label: "Border Collie" },
  { id: DogBreed.Coonhound, label: "Coonhound" },
  { id: DogBreed.CorgiCardigan, label: "Cardigan Corgi" },
  { id: DogBreed.Cotondetulear, label: "Cotondetulear" },
  { id: DogBreed.Dachshund, label: "Dachshund" },
  { id: DogBreed.Dalmatian, label: "Dalmatian" },
  { id: DogBreed.DaneGreat, label: "Great Dane" },
  { id: DogBreed.DeerhoundScottish, label: "Scottish Deerhound" },
  { id: DogBreed.Dhole, label: "Dhole" },
  { id: DogBreed.Dingo, label: "Dingo" },
  { id: DogBreed.Doberman, label: "Doberman" },
  { id: DogBreed.ElkhoundNorwegian, label: "Norwegian Elkhound" },
  { id: DogBreed.Entlebucher, label: "Entlebucher" },
  { id: DogBreed.Eskimo, label: "Eskimo" },
  { id: DogBreed.FinnishLapphund, label: "Lapphund Finnish" },
  { id: DogBreed.FriseBichon, label: "Bichon Frise" },
  { id: DogBreed.Germanshepherd, label: "Germanshepherd" },
  { id: DogBreed.GreyhoundItalian, label: "Italian Greyhound" },
  { id: DogBreed.Groenendael, label: "Groenendael" },
  { id: DogBreed.Havanese, label: "Havanese" },
  { id: DogBreed.HoundAfghan, label: "Afghan Hound" },
  { id: DogBreed.HoundBasset, label: "Basset Hound" },
  { id: DogBreed.HoundBlood, label: "Blood Hound" },
  { id: DogBreed.HoundEnglish, label: "English Hound" },
  { id: DogBreed.HoundIbizan, label: "Ibizan Hound" },
  { id: DogBreed.HoundPlott, label: "Plott Hound" },
  { id: DogBreed.HoundWalker, label: "Walker Hound" },
  { id: DogBreed.Husky, label: "Husky" },
  { id: DogBreed.Keeshond, label: "Keeshond" },
  { id: DogBreed.Kelpie, label: "Kelpie" },
  { id: DogBreed.Komondor, label: "Komondor" },
  { id: DogBreed.Kuvasz, label: "Kuvasz" },
  { id: DogBreed.Labradoodle, label: "Labradoodle" },
  { id: DogBreed.Labrador, label: "Labrador" },
  { id: DogBreed.Leonberg, label: "Leonberg" },
  { id: DogBreed.Lhasa, label: "Lhasa" },
  { id: DogBreed.Malamute, label: "Malamute" },
  { id: DogBreed.Malinois, label: "Malinois" },
  { id: DogBreed.Maltese, label: "Maltese" },
  { id: DogBreed.MastiffBull, label: "Bull Mastiff" },
  { id: DogBreed.MastiffEnglish, label: "English Mastiff" },
  { id: DogBreed.MastiffTibetan, label: "Tibetan Mastiff" },
  { id: DogBreed.Mexicanhairless, label: "Mexicanhairless" },
  { id: DogBreed.Mix, label: "Mix" },
  { id: DogBreed.MountainBernese, label: "Bernese Mountain" },
  { id: DogBreed.MountainSwiss, label: "Swiss Mountain" },
  { id: DogBreed.Newfoundland, label: "Newfoundland" },
  { id: DogBreed.Otterhound, label: "Otterhound" },
  { id: DogBreed.OvcharkaCaucasian, label: "Caucasian Ovcharka" },
  { id: DogBreed.Papillon, label: "Papillon" },
  { id: DogBreed.Pekinese, label: "Pekinese" },
  { id: DogBreed.Pembroke, label: "Pembroke" },
  { id: DogBreed.PinscherMiniature, label: "Miniature Pinscher" },
  { id: DogBreed.Pitbull, label: "Pitbull" },
  { id: DogBreed.PointerGerman, label: "German Pointer" },
  { id: DogBreed.PointerGermanlonghair, label: "Germanlonghair Pointer" },
  { id: DogBreed.Pomeranian, label: "Pomeranian" },
  { id: DogBreed.PoodleMedium, label: "Medium Poodle" },
  { id: DogBreed.PoodleMiniature, label: "Miniature Poodle" },
  { id: DogBreed.PoodleStandard, label: "Standard Poodle" },
  { id: DogBreed.PoodleToy, label: "Toy Poodle" },
  { id: DogBreed.Pug, label: "Pug" },
  { id: DogBreed.Puggle, label: "Puggle" },
  { id: DogBreed.Pyrenees, label: "Pyrenees" },
  { id: DogBreed.Redbone, label: "Redbone" },
  { id: DogBreed.RetrieverChesapeake, label: "Chesapeake Retriever" },
  { id: DogBreed.RetrieverCurly, label: "Curly Retriever" },
  { id: DogBreed.RetrieverFlatcoated, label: "Flatcoated Retriever" },
  { id: DogBreed.RetrieverGolden, label: "Golden Retriever" },
  { id: DogBreed.RidgebackRhodesian, label: "Rhodesian Ridgeback" },
  { id: DogBreed.Rottweiler, label: "Rottweiler" },
  { id: DogBreed.Saluki, label: "Saluki" },
  { id: DogBreed.Samoyed, label: "Samoyed" },
  { id: DogBreed.Schipperke, label: "Schipperke" },
  { id: DogBreed.SchnauzerGiant, label: "Giant Schnauzer" },
  { id: DogBreed.SchnauzerMiniature, label: "Miniature Schnauzer" },
  { id: DogBreed.SegugioItalian, label: "Italian Segugio" },
  { id: DogBreed.SetterEnglish, label: "English Setter" },
  { id: DogBreed.SetterGordon, label: "Gordon Setter" },
  { id: DogBreed.SetterIrish, label: "Irish Setter" },
  { id: DogBreed.Sharpei, label: "Sharpei" },
  { id: DogBreed.SheepdogEnglish, label: "English Sheepdog" },
  { id: DogBreed.SheepdogShetland, label: "Shetland Sheepdog" },
  { id: DogBreed.Shiba, label: "Shiba" },
  { id: DogBreed.Shihtzu, label: "Shihtzu" },
  { id: DogBreed.SpanielBlenheim, label: "Blenheim Spaniel" },
  { id: DogBreed.SpanielBrittany, label: "Brittany Spaniel" },
  { id: DogBreed.SpanielCocker, label: "Cocker Spaniel" },
  { id: DogBreed.SpanielIrish, label: "Irish Spaniel" },
  { id: DogBreed.SpanielJapanese, label: "Japanese Spaniel" },
  { id: DogBreed.SpanielSussex, label: "Sussex Spaniel" },
  { id: DogBreed.SpanielWelsh, label: "Welsh Spaniel" },
  { id: DogBreed.SpitzJapanese, label: "Japanese Spitz" },
  { id: DogBreed.SpringerEnglish, label: "English Springer" },
  { id: DogBreed.StBernard, label: "Saint Bernard" },
  { id: DogBreed.TerrierAmerican, label: "American Terrier" },
  { id: DogBreed.TerrierAustralian, label: "Australian Terrier" },
  { id: DogBreed.TerrierBedlington, label: "Bedlington Terrier" },
  { id: DogBreed.TerrierBorder, label: "Border Terrier" },
  { id: DogBreed.TerrierCairn, label: "Cairn Terrier" },
  { id: DogBreed.TerrierDandie, label: "Dandie Terrier" },
  { id: DogBreed.TerrierFox, label: "Fox Terrier" },
  { id: DogBreed.TerrierIrish, label: "Irish Terrier" },
  { id: DogBreed.TerrierKerryblue, label: "Kerryblue Terrier" },
  { id: DogBreed.TerrierLakeland, label: "Lakeland Terrier" },
  { id: DogBreed.TerrierNorfolk, label: "Norfolk Terrier" },
  { id: DogBreed.TerrierNorwich, label: "Norwich Terrier" },
  { id: DogBreed.TerrierPatterdale, label: "Patterdale Terrier" },
  { id: DogBreed.TerrierRussell, label: "Russell Terrier" },
  { id: DogBreed.TerrierScottish, label: "Scottish Terrier" },
  { id: DogBreed.TerrierSealyham, label: "Sealyham Terrier" },
  { id: DogBreed.TerrierSilky, label: "Silky Terrier" },
  { id: DogBreed.TerrierTibetan, label: "Tibetan Terrier" },
  { id: DogBreed.TerrierToy, label: "Toy Terrier" },
  { id: DogBreed.TerrierWelsh, label: "Welsh Terrier" },
  { id: DogBreed.TerrierWesthighland, label: "Westhighland Terrier" },
  { id: DogBreed.TerrierWheaten, label: "Wheaten Terrier" },
  { id: DogBreed.TerrierYorkshire, label: "Yorkshire Terrier" },
  { id: DogBreed.Tervuren, label: "Tervuren" },
  { id: DogBreed.Vizsla, label: "Vizsla" },
  { id: DogBreed.WaterdogSpanish, label: "Spanish Waterdog" },
  { id: DogBreed.Weimaraner, label: "Weimaraner" },
  { id: DogBreed.Whippet, label: "Whippet" },
  { id: DogBreed.WolfhoundIrish, label: "Irish Wolfhound" },
];

export default DOG_BREEDS;
